### ISSUE TITLE
"java.lang.NoSuchMethodError" When trying to start minecraft

### ISSUE THREAD

**Issue by StrandedPasta** [gegy1000/Terrarium#100]
[Nosuchmethod.txt](https://github.com/gegy1000/Terrarium/files/4843834/Nosuchmethod.txt)

Tried to play with the recent updated and for some reason it crashes upon startup. I know its from this mod since it works just fine without it. Any idea why this is happening?

P.S. Hope this doesn't take too long to solve cause Id love to see the changes that this mod has other then crashing the game~

**Comment by Gegy** [comment]
You can solve this by updating Forge :)
