### ISSUE TITLE
Cubic Chunks support

### ISSUE THREAD

**Issue by Gegy** [gegy1000/Terrarium#11]
It would be ideal if this mod supported Cubic Chunks, allowing 1:1 scale worlds without much of the world being "chopped off" at 256 blocks above the ocean.

**Comment by vico93** [comment]
Although Cubic Chunks breaks a lot of other mods i would support a version to work with that.

**Comment by Gegy** [comment]
I've talked with the Cubic Chunks people a bit about this -- the API is currently undergoing a rework. I will wait for that before implementing this.

**Comment by juh9870** [comment]
So, in latest 4 commits CC compat was finally added or i should wait a bit more before compiling and testing?

**Comment by Gegy** [comment]
CC compat has been in the works for the past few months, though it is still very much WIP. A lot of functionality is not yet implemented for it

**Comment by Xorbah** [comment]
Can't wait to see this.
