### ISSUE TITLE
Search bar in geotool doesn't work

### ISSUE THREAD

**Issue by thyblank** [gegy1000/Terrarium#111]
On pretty much every new version, the search bar does absolutely nothing. Typing something in it doesn't bring up anything and it's slightly bothersome whenever I wanna search directly for a specific city or country but I can't use it. One of the past versions it worked fine but it hasn't worked for quite a while now.
![Capture](https://user-images.githubusercontent.com/29050780/116807365-736bfb80-aaf8-11eb-87e1-8a5e41c85733.PNG)

**Comment by Gegy** [comment]
Have you configured the mod to use the OpenStreetMap / Nominatim Geocoder by any chance?

**Comment by thyblank** [comment]
not particularly, how do you change it?

**Comment by thyblank** [comment]
oh I found it, gonna check if it works

**Comment by thyblank** [comment]
![Capture](https://user-images.githubusercontent.com/29050780/116807748-74059180-aafa-11eb-961c-4c2ea603fe8f.PNG)
Still nothing sadly :(
typing: "/geotp canada" works fine tho

**Comment by Gegy** [comment]
Hmm, that's weird! Will take a look into this- I can see on the Google API end that requests have been coming in, so I'm not sure what's breaking here. Maybe the API response format changed. 😄

**Comment by thyblank** [comment]
well, either way, I think you're doing a good job. Keep up ur good work, really enjoying the mod :)

**Comment by Gegy** [comment]
Apologies for leaving this issue for so long! I think I have found the issue and will be pushing a release shortly to resolve it. :)
