### ISSUE TITLE
can't use geotp and crasho if I teleport with the journery map mod to areas I've already explored

### ISSUE THREAD

**Issue by Vincenzo980** [gegy1000/Terrarium#120]
> I tried to reinstall terrarium both the mod and to delete the data folder obviously creating a copy but in that case it tells me not to be connected to the internet in the initialization upload

**Comment by Vincenzo980** [comment]
[](url
![Screenshot (11)](https://user-images.githubusercontent.com/110442174/182288035-29930572-a287-42cd-9364-faff9dff22f7.png)
)

**Comment by Vincenzo980** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/110442174/182288111-0c01ff37-4964-4680-b064-d3015399601c.png)

**Comment by Gegy** [comment]
Hi! It looks like you might have an out-of-date Java version causing troubles- are you using the Vanilla Minecraft launcher? 🙂

**Comment by Vincenzo980** [comment]
I updated java but still not going I use the normal launcher of minecraft premium with forge 1.12.2 now I try to reinstall both java and minecraft that forge

**Comment by Vincenzo980** [comment]
I tried to reinstall everything but I still do not work would you have any solution?

**Comment by Vincenzo980** [comment]
[](url)
![image](https://user-images.githubusercontent.com/110442174/182425457-cbe103ab-20d5-4868-96fd-a2f0a2b7e0fc.png)
When I try to reset and delete the created data I get this I can not use in any way

**Comment by Vincenzo980** [comment]
And a problem that other friends I used to play with are also experiencing so it's not just my problem

**Comment by Gegy** [comment]
Would you be able to send the `.minecraft/logs/latest.log` file from when this happens? 🙂

**Comment by Vincenzo980** [comment]
[](url
[2022-08-02-1.log.gz](https://github.com/Gegy/Terrarium/files/9244930/2022-08-02-1.log.gz)
[)](url
[2022-08-02-2.log.gz](https://github.com/Gegy/Terrarium/files/9244934/2022-08-02-2.log.gz)
[2022-08-02-3.log.gz](https://github.com/Gegy/Terrarium/files/9244935/2022-08-02-3.log.gz)
[latest.log](https://github.com/Gegy/Terrarium/files/9244937/latest.log)

)

**Comment by Gegy** [comment]
Thanks for sharing these, this is super weird! If you have a Java 8 install locally, I recommend attempting to set your Forge 1.12 profile to point to this- currently it's using the default one installed by the launcher, but it looks like it somehow has gotten into a very broken state. I'm not really sure what causes this, but I've seen someone else encounter this where reinstalling Java and pointing Minecraft to that version works.

If you don't already have a Java 8 version installed, you can find it [here](https://www.java.com/en/download/). 🙂 It should install into `C:/Program Files/Java/jre1.8.0_341/bin/javaw.exe` which you can reference from the Minecraft launcher under More Options >> Java Executable 🙂 

Let me know if I can help in any other way!

**Comment by Vincenzo980** [comment]
I already java 8 and I understood that it must replace java installed by minecraft with the online one but I have not well understood how I have to do could you explain it again?

**Comment by Vincenzo980** [comment]
I already java 8 and I understood that it must replace java installed by minecraft with the online one but I have not well understood how I have to do could you explain it again?

**Comment by Vincenzo980** [comment]
Thank you very much for the help now goes

**Comment by Vincenzo980** [comment]
However the problems started after I teleported to the town of Pula in Istria even now and I happened again that when I teleported there it was all black and did not charge but this time it did not crash the world

**Comment by Vincenzo980** [comment]
You know how you can do the same process on t launcher for a friend of mine

**Comment by Gegy** [comment]
I have looked into this and found a potential fix (see: #121), and should be pushing a release shortly. There's a test build linked in that issue if you would like to test in the meantime- please do let me know if you encounter any issues. Apologies for the trouble! 🙂
