### ISSUE TITLE
Failed to prepare terrarium for use. check your internet connection.

### ISSUE THREAD

**Issue by Gamersooreal** [gegy1000/Terrarium#122]
First i thought it was my internet then i switched and this error kept showing up. i re installed the mod and every thing but it still dont work
![Screenshot 2022-08-08 114042](https://user-images.githubusercontent.com/110807178/183350914-fb8c9b0d-badb-4fbf-8ff8-aa0662e0709d.png)

**Comment by Gegy** [comment]
Hey! Thank you for the report, and apologies for the trouble! We're currently tracking this in #121 🙂
