### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by Imtajfti7** [gegy1000/Terrarium#123]
Hi. I am currently experiencing multiple issues with this mod. I've had this mod installed for a while and have also played it for a while and have never had any problems, but for some reason now I'm having problems. First issue is that when I'm trying to generate a new world, if I try to select any location other than the default one, the preview window literally just shows flat grass. No matter how much I mess with the sliders, it stays the exact same.
![Screenshot (193)](https://user-images.githubusercontent.com/111089532/184238400-16c48717-d7ca-4aa8-a377-584559a3ff53.png)
![Screenshot (194)](https://user-images.githubusercontent.com/111089532/184238499-dfa0c6c2-cd85-4a7f-8c53-bfeaeb481274.png)
Here you can see the location I selected.
If I try to create the world with that preview, I spawn in the void and just fall with no generated terrain. 
 Next issue is that if I go in and out of the generate window and the spawn selector map too many times, the game "crashes". I have VanillaFix so the game doesn't actually crash, but in theory it does, and it displays this error. 
![Screenshot (192)](https://user-images.githubusercontent.com/111089532/184238800-e1fa90e9-777f-4096-9834-4a4a7902e727.png) 
When I tried to click on the Get Link button, it said "failed" so whatever, but I'm just making you aware of that error.
Also, when I load in to my previous world that has always worked fine, everything works, but it displays an error message in the corner saying "Terrarium failed to load 7 data packs" or something like that. I apologize because I can't remember the exact wording, but it was something like that. Anyway these issues are mildly frustrating as I really wanted to play today, and now I can't because of this. If you could help me with this it would be greatly appreciated. Thanks!

**Comment by Gegy** [comment]
Hey! Thank you for the report, and apologies for the trouble! We're currently tracking this in #121 🙂
