### ISSUE TITLE
Failed to prepare Terrarium for use!

### ISSUE THREAD

**Issue by BearThicklegs** [gegy1000/Terrarium#129]
Hey so I have used this mod for awhile and have really enjoyed playing it but lately I have been unable to create any new worlds using the Earth world type. Regardless of any settings I always receive an error saying: Failed to prepare Terrarium for use! Please check your internet connection and try again.

I am using the latest Terrarium version from Curseforge 1.1.9
My internet is perfectly fine it can handle streaming and all forms of online gaming with no issues.
I first noticed this error with the 1.1.8 version and upgraded hoping it would be fixed.
This issue seemingly spontaneously occurred it was working until it didn't basically I was using the mod but took a break from Minecraft for a few months came back and it wasn't working.

Would love help fixing this there really isn't any alternatives to this mod. Thanks for any help.

**Comment by ekat2468** [comment]
I'm having a similar issue not really sure what to do tho

**Comment by kostyakoriginal** [comment]
Similar problem, tried everything but the mod still writes "Internet connection error" although I have a good connection and updated all the software to the latest version.

**Comment by BearThicklegs** [comment]
Thank you the new update did indeed fix the issue for me, I can now return to enjoying one of my legitimately favorite mods
