### ISSUE TITLE
Failed to load from data source and infinite ocean

### ISSUE THREAD

**Issue by williambl** [gegy1000/Terrarium#30]
I've compiled from commit d415403 and I get this error while generating chunks: https://pastebin.com/wEnPcqK2

The result is an infinite ocean with a depth of 1 and a floor of quartz at y=6.

This is what it looks like:
![Screenshot](https://user-images.githubusercontent.com/5115825/42409756-0c0b3a52-81d7-11e8-9582-c208a4864486.png)

**Comment by Gegy** [comment]
Was migrating the data to a new server and changing its format. (#16)
