### ISSUE TITLE
Damavand Mountain Inconsistency

### ISSUE THREAD

**Issue by SinaMegapolis** [gegy1000/Terrarium#35]
so yeah the mod have some things that should've been other things (if you know what i mean :mr_bean:)

for example i used locations of a distiguished volcano
it should have a lot of snow and a hole on top but it has "trees" instead (u wot)
i mean just look at this reee https://imgur.com/PDh71JC
also there should be a config options for generating caves from user-given datas

k thx bye

**Comment by Gegy** [comment]
Can you give a picture of the real volcano and a name / coordinates? :P

**Comment by SinaMegapolis** [comment]
Damavand Mountain
 35°57'17.04"N  52° 6'35.11"E
here's a pic from google earth: https://imgur.com/dqoYpjH
