### ISSUE TITLE
Cave and ore generation does not occur at high altitudes 

### ISSUE THREAD

**Issue by genandnic** [gegy1000/Terrarium#60]
If you decide to play on the survival preset, you have to make sure your spawn is somewhere near sea level, or else you'll have a hard time finding caves and ores because they still generate at the same Y level everywhere.

**Comment by Gegy** [comment]
Would have to add a config option for a custom ore generator -- which would unfortunately mean no mod compatibility. However, it's definitely a feature I want to add.
