### ISSUE TITLE
Whether port The Terrarium on The Minecraft 1.13/1.14?

### ISSUE THREAD

**Issue by ghost** [gegy1000/Terrarium#62]
I want to know, whether or not? And still, there's at of the mod an core of the Earth. It's simple a question.

**Comment by Gegy** [comment]
Yes. When Forge is released for those versions, it will be ported.

**Comment by ghost** [comment]
Alright.

**Comment by Gegy** [comment]
Closing because it's on my list once CubicChunks updates 🙂
