### ISSUE TITLE
Keeps crashing after I teleport after a teleport

### ISSUE THREAD

**Issue by R0X0RE0** [gegy1000/Terrarium#64]
So whenever I do a world scale that is 1:1, it crashes after I teleport after a teleport. For example, I teleport from Mount Everest to New York, then New York to Los Angeles. Well, if I try to teleport from New York to Los Angeles, it crashes the game. Please fix.

**Comment by Gegy** [comment]
Apologies, not sure how I completely missed responding to this issue. _Only 4 months late_ :P
If you're still having this issue, would you be able to provide a crash report? Thanks!
