### ISSUE TITLE
Crash when selecting 'Where I Am?' option on /geotool

### ISSUE THREAD

**Issue by vico93** [gegy1000/Terrarium#68]
Seems to be somewhat related with @Vazkii 's [Quark](https://github.com/Vazkii/Quark).

https://paste.dimdev.org/muyuquhivu.mccrash

Using terrarium-1.0.0, Quark-r1.5-146 and AutoRegLib-1.3-26

[Issue on Quark's side.](https://github.com/Vazkii/Quark/issues/1162)

**Comment by Gegy** [comment]
Going to close due to it rather being an issue on AutoRegLib's side

**Comment by vico93** [comment]
OH i was wondering what was ARL @yrsegal was saying, thanks to clarify
