### ISSUE TITLE
Buttons look wrong in customization UI at high resolution

### ISSUE THREAD

**Issue by calloatti** [gegy1000/Terrarium#72]
When minecraft is maximized in a 1920x1080 monitor, buttons look like this:

![2019-03-31_13 27 22](https://user-images.githubusercontent.com/12817862/55291776-37b25500-53b9-11e9-84dd-dd635a5e8ee7.png)

Making the game window smaller, buttons draw correctly:

![2019-03-31_13 26 50](https://user-images.githubusercontent.com/12817862/55291784-51539c80-53b9-11e9-9874-e7fb0cd0c22d.png)

Also, when you are in one of the World/Feature/Survival properties screen, resizing the game window by click drag of the window border or by clicking the maximize/restore button in the top right corner, the UI goes back one menu level.

BEFORE:

![2019-03-31_13 34 06](https://user-images.githubusercontent.com/12817862/55291815-b909e780-53b9-11e9-9869-a65750210e24.png)

AFTER CLICKING MAXIMIZE BUTTON IN TOP RIGHT:

![2019-03-31_13 34 56](https://user-images.githubusercontent.com/12817862/55291826-cc1cb780-53b9-11e9-9964-9cc440fe4c11.png)

**Comment by Gegy** [comment]
Hm, that's really odd. I test at 1920x1080, and have never encountered this. Could it perhaps be related to the resourcepack?

**Comment by calloatti** [comment]
I will set up a clean install with only your mod and report back. I am not using any resource packs anyway, but I do have 100+ mods besides this one.

**Comment by calloatti** [comment]
It still happens when the only mod is Terrarium.

Full log: https://paste.ee/p/pMAPM

**Comment by calloatti** [comment]
![image](https://user-images.githubusercontent.com/12817862/56089253-68d55f80-5e66-11e9-868e-e6051ab4b054.png)

Make the window bigger: 

![image](https://user-images.githubusercontent.com/12817862/56089267-8a364b80-5e66-11e9-8330-30100bb4f5d7.png)

Resize width a bit:

![image](https://user-images.githubusercontent.com/12817862/56089273-adf99180-5e66-11e9-939b-a5edd936c6b5.png)

More:

![image](https://user-images.githubusercontent.com/12817862/56089276-b782f980-5e66-11e9-9ad8-d483a6d36759.png)

More:

![image](https://user-images.githubusercontent.com/12817862/56089277-be117100-5e66-11e9-9526-3ac6ff339080.png)

F3:

![image](https://user-images.githubusercontent.com/12817862/56089301-1d6f8100-5e67-11e9-85bf-9425fc8f8e7e.png)

Maybe it's the Intel UHD Video?

**Comment by Gegy** [comment]
Hmm. Not sure why I don't see this issue at all, definitely could be weird specific GPU behaviour. However, I have found a solution that *should* resolve this.
