### ISSUE TITLE
Game stops responding after buying an empty map from a cartographer villager

### ISSUE THREAD

**Issue by calloatti** [gegy1000/Terrarium#73]
Buying an empty map from a cartographer villager makes the game to stop responding. You can still move around but cannot open the trade GUI anymore. The game does not crash but trying to exit the game just freezes.

Log, where some errors are reported as soon as you buy the empty map (at the end):

https://paste.ee/p/iJrYF

This is a multi player game using "Open to Lan".

The game also crashes when picking up a treasure map from the mod Quark. In that case reloading the game still crashes, and the only way to solve is to restore from backup (Or maybe editing the player inventory and deleting the Quark map). 

I have no log of that error but I guess it must be the same reason.

**Comment by Gegy** [comment]
Thanks for the report! I think I know the issue here, although not sure a solution. Will look into it.

**Comment by calloatti** [comment]
Same problem when using the command:

`/locate Monument`

I guess default config survival worlds do not have any ocean monuments due to the default depth of the oceans, so this somehow fails the same way as the cartographer empty map.

/locate Village works with no problem, finding the nearest village

**Side Note:** 

Maybe oceans should have a default depth that allows for ocean monuments to spawn?

Maybe x blocks from the coast oceans should become deep oceans to allow for ocean monuments?

Maybe add an option for ocean size (radius) like beaches, and make the oceans deeper and the biome _deep ocean_ after that radius ?

Should I open a new issue for this?

**Comment by Gegy** [comment]
Yeah, a new issue would be great

**Comment by Gegy** [comment]
This should be fixed in 1.1.0 :)
