### ISSUE TITLE
Problems with water edges.

### ISSUE THREAD

**Issue by calloatti** [gegy1000/Terrarium#74]
Default settings, only terrarium mod.

![image](https://user-images.githubusercontent.com/12817862/56212382-42632000-6030-11e9-898c-bbdfe10523ca.png)

![image](https://user-images.githubusercontent.com/12817862/56212458-73dbeb80-6030-11e9-8fc9-34ec53664ab1.png)

![image](https://user-images.githubusercontent.com/12817862/56212489-7dfdea00-6030-11e9-95b8-2bfc2bd15240.png)

Log: https://paste.ee/p/vepYk

**Comment by Gegy** [comment]
Definitely an interesting one, need to look into it! Thanks for reporting

**Comment by Gegy** [comment]
This is fixed in 1.1.0
