### ISSUE TITLE
 Bugged sunflowers on water lakes

### ISSUE THREAD

**Issue by calloatti** [gegy1000/Terrarium#75]
Default settings, only terrarium mod:

Bugged sunflowers missing the bottom half spawn over water lakes. When you get near the lake, flowers start to vanishrandomly.

If you break a sunflower, nothing drops.

![image](https://user-images.githubusercontent.com/12817862/56212748-0aa8a800-6031-11e9-852c-24770b3ba473.png)

![image](https://user-images.githubusercontent.com/12817862/56212771-1300e300-6031-11e9-80b8-44fbfd7ce93b.png)

![image](https://user-images.githubusercontent.com/12817862/56212780-18f6c400-6031-11e9-9e79-3929a9d3e8b7.png)

**Comment by Gegy** [comment]
Ah, yeah. The way I am currently generating grass is very unconventional (essentially, result is it generates before lakes) Vanilla generates grass after lakes. Not sure why I decided to work generation like that, I am currently in the works of rewriting decoration to work completely different. I believe this'll no longer be an issue following that change.

**Comment by Gegy** [comment]
Fixed in 1.1.0 :)
