### ISSUE TITLE
Is this normal? farmland and crops all over, random fences everywhere.

### ISSUE THREAD

**Issue by calloatti** [gegy1000/Terrarium#76]
Default config, only terrarium mod.

![image](https://user-images.githubusercontent.com/12817862/56212904-578c7e80-6031-11e9-8357-38d38d230eb9.png)

![image](https://user-images.githubusercontent.com/12817862/56212935-670bc780-6031-11e9-9fcd-dfe2a483847d.png)

Are the fences the actual boundaries of counties/provinces?

**Comment by Gegy** [comment]
Yeah, this is normal generation. Though, not very good generation. In reality, these areas are actually farms. I think it's quite easy to forget how much of our world is farmland -- this definitely surprised me. However, just based on how unexpected and unnatural it feels, I want to change how they generate to rather not be farmland. :P

With the current generation, the boundaries are completely random. Interesting concept, though, to generate boundaries somehow! Would like to implement that at some point.

**Comment by Gegy** [comment]
Fixed in 1.1.0 :)
