### ISSUE TITLE
sponge crash on server boot

### ISSUE THREAD

**Issue by IronworksProductions** [gegy1000/Terrarium#82]
crash log:https://gist.github.com/nacjm/8e4f02ab88ca5c30c641729135a43fc7

**Comment by Gegy** [comment]
Weird. I believe this would more likely be an incompatibility with one of the other mods you have installed -- maybe try run the mod with just Sponge and Terrarium?

**Comment by IronworksProductions** [comment]
It seems this is connected to dalekmod also after further testing. just sponge and terrarium works fine

**Comment by IronworksProductions** [comment]
and compact machines? https://gist.github.com/nacjm/1f1dea946f710aba0eea815fc6e1475a

**Comment by IronworksProductions** [comment]
I am almost positive now I will crash from every mod with modded dimensions with sponge installed
this runs without sponge on the modpack. but with it it crashes constantly

**Comment by Gegy** [comment]
Okay. This makes sense: Terrarium only initialises itself for the overworld, but the dimensions from these two mods do not override the biome provider, so it tries to use Terrarium's biome provider (but that crashes, because it is not initialised)

**Comment by IronworksProductions** [comment]
so how do we fix it?

**Comment by Gegy** [comment]
Unfortunately until this is fixed the only option is to remove either Terrarium or the mods that are causing issues. 

In terms of fixing it, it can be done on Terrarium's side. It's not an ideal fix but this is a generally odd situation where arguably neither side is at 'fault'. I'll try get a patch out today :)

**Comment by IronworksProductions** [comment]
should I build the dev build or wait for you to release a build with this patch?

**Comment by Gegy** [comment]
Feel free to build yourself from the [1.12 branch](https://github.com/gegy1000/Terrarium/tree/1.12) (you probably don't want 1.12-dev)
Otherwise, I'll get a release out today some time

**Comment by IronworksProductions** [comment]
here is another bug coming from sponge after it runs for a time. Ticking world crash this time. https://gist.github.com/nacjm/806a41404c6ee3011280b556ce32004c

**Comment by Gegy** [comment]
This looks like it might be an issue with one of the other mods again. Maybe try run on a vanilla world without Terrarium and see if the crash still happens?
