### ISSUE TITLE
Game crashes, when trying to select the Terrarium world type (Earth / Survival)

### ISSUE THREAD

**Issue by MiniStumpy** [gegy1000/Terrarium#83]
When I try to select the terrarium world type, the game crashes. 
I'm using forge 1.12.2, some mods and Terrarium 1.0.3 (The mods can be seen in the crash report)
Here is the crash report:
[crash-2019-12-29_10.59.33-client.txt](https://github.com/gegy1000/Terrarium/files/4007954/crash-2019-12-29_10.59.33-client.txt)

**Comment by Gegy** [comment]
Hi, this mod is currently not compatible with CubicChunks 🙁
