### ISSUE TITLE
Deserts misrepresented by low-lying forests in Africa

### ISSUE THREAD

**Issue by RRyyas** [gegy1000/Terrarium#90]
So i decided to create a 1:100 survival world in Africa using this mod, but when exploring a bit i noticed that most deserts are missing in East Africa. I then created another world in 1:200, and mapped the entire country of Kenya, a biome diverse country in real life, to show you how severe this problem is.
Screenshots: https://imgur.com/a/q6FZFLi

**Comment by Gegy** [comment]
Thanks for the report! This is definitely something I’m trying to improve with additional data. I’m integrating temperature, rainfall and soil data so hopefully that can allow it to be more accurate :)

**Comment by RRyyas** [comment]
Thanks for responding. I have a source for the temperature and rainfall data that you might need: https://www.worldclim.org/data/worldclim21.html
The data is at minimum 1x1 km per pixel, so interpolation is needed for the data

**Comment by Gegy** [comment]
WorldClim is very cool, am already using it :)

**Comment by Gegy** [comment]
This has been reworked in 1.1.0, so closing for now :)
