### ISSUE TITLE
Nether and End won't generate normally

### ISSUE THREAD

**Issue by zoemaestra** [gegy1000/Terrarium#91]
The Nether and the End dimensions won't generate properly when using the mod. The End will load and you can enter it, but only the obsidian platform and empty bedrock exit portal generate. The Nether doesn't load at all and just stays on the loading screen.

**Comment by RRyyas** [comment]
I got this issue as well when creating a custom map of the End dimension in WorldPainter. Basically, it's a map of the Moon, and i made the spawn location inside a crater. Only the end pillars and the ender dragon generated, and the chorus plants along with the portals outside generated.

**Comment by JAcamp1** [comment]
Ok, this is still probably the most game-breaking issue there is. All dimensions except for some reason Galacticraft's moon are horribly messed up while generating. Multiplayer and singleplayer worlds cannot function properly as the server will hang as soon as someone enters a portal. Would there be a way to simply disable this mods generation when in other dimensions?

**Comment by Gegy** [comment]
This should be resolved in https://github.com/Gegy/Terrarium/commit/b227abe16450cca26e5482164a7d8a95e5a79702
