### ISSUE TITLE
Strongholds don't spawn uniformly around the map

### ISSUE THREAD

**Issue by RRyyas** [gegy1000/Terrarium#93]
I noticed that when i was reaching the end of the game in survival, i placed an ender eye, and it would point towards 0,0, which is at West Africa. I then did /locate Stronghold to see where exactly it would spawn, and it said "Located Stronghold at 23576 (y?) -4664", which is about 15,000 blocks away from where i am in Africa. This makes travelling to strongholds really difficult, especially when you are in Asia or America, and the strongholds spawn close to 0,0 like in vanilla minecraft.

**Comment by Gegy** [comment]
Fixed in 1.1.0 :)
