### ISSUE TITLE
Given world does not support column generation

### ISSUE THREAD

**Issue by EnvyEnfys** [gegy1000/Terrarium#95]
My console spat out this

06.05 22:43:34 [Server] ERROR 0: NORMAL
06.05 22:43:34 [Server] ERROR 1: ASM: class epicsquid.mysticalworld.events.CapabilityHandler attackCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
06.05 22:43:34 [Server] ERROR 2: ASM: class vazkii.quark.base.capability.CapabilityHandler attachItemCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
06.05 22:43:34 [Server] ERROR 3: ASM: class vazkii.quark.base.capability.CapabilityHandler attachTileCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
06.05 22:43:34 [Server] ERROR 4: ASM: class gr8pefish.ironbackpacks.core.EventHandler attachPlayerCaps(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
06.05 22:43:34 [Server] ERROR 5: ASM: vazkii.quark.management.feature.RightClickAddToShulkerBox@4d3bf6f0 onAttachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
06.05 22:43:34 [Server] ERROR 6: ASM: vazkii.quark.vanity.feature.BoatSails@20901d91 onBoatGenesis(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
06.05 22:43:34 [Server] ERROR 7: ASM: com.buuz135.despawningspawners.DespawningSpawners@589d0788 onAttachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
06.05 22:43:34 [Server] ERROR 8: ASM: mcjty.theoneprobe.ForgeEventHandlers@7989aa7c onEntityConstructing(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
06.05 22:43:34 [Server] ERROR 9: ASM: ivorius.reccomplex.events.handlers.RCForgeEventHandler@7edbf8c4 onEntityCapapabilityAttach(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
06.05 22:43:34 [Server] ERROR 10: ASM: slimeknights.tconstruct.gadgets.item.ItemPiggybackPack@266adfa8 attachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V

Only happens with the version 1.1.0

**Comment by EnvyEnfys** [comment]
Also had at the top of the crash log Given world does not support column generation

**Comment by Gegy** [comment]
Fixed in 1.1.0 :)
