### ISSUE TITLE
No longer pulling elevation geodata properly

### ISSUE THREAD

**Issue by VisionaryMind** [gegy1000/Terrarium#99]
Starting this morning (6/25/20), it appears there is a ceiling to max elevation. Everything is plateaued at a certain point. This happens at any point in the world except for those locations below the "cut off". This is likely not a problem with the mod, but rather the systems it is pulling data from.

**Comment by Gegy** [comment]
Hmm, might this just relate to the vanilla world height limit? Do you have CubicChunks installed?

**Comment by VisionaryMind** [comment]
No, this was working for all of these locations yesterday. I thought it might be my installation, so I created a new Forge 1.12.2 vanilla profile and installed only this module. Are you able to generate new worlds now on your end? It occurred to me that the geo-systems might be blocking my VPN, but I tried multiple locations around the globe, and it's always the same thing. I will also try a non-VPN connection to rule that out.

**Comment by Gegy** [comment]
So this is definitely not occurring at y=255? Did the world scale change by any chance?

**Comment by VisionaryMind** [comment]
This isn't working for anyone. I have confirmed with 5 other people that have been using it. I also just got a brand new laptop (with nothing installed on it). Installed Minecraft JE, Forge 1.12 - 14.21.1.2387, and the 1.1.1 Terrarium mod -- nothing else. Even the default spawnpoint in Tibet(?) doesn't work. It's completely flat. You will see what I mean if you create a fresh new Minecraft installation --- I don't think this is a problem with the mod or with Minecraft parameters. It seems to be something the geo-systems are doing.

**Comment by Gegy** [comment]
Data source is doing all fine, and on a fresh instance, everything is working fine for me.

![](https://i.imgur.com/8B9eR0x.png)

Are you *sure* that the terrain is not being cut off at y=255? It is impossible for this to be an issue with the data source- I'm hosting all the data, and I haven't touched it :P

**Comment by VisionaryMind** [comment]
I just left-clicked on a tile and I do see the "height limit for building is 255 blocks", so your assumption was right. The question I now have is -- why was this building at proper elevation yesterday and now, all of a sudden, everything has been shifted up past the threshold? It happens for me on all new / fresh builds, on different computers. It's completely baffling.

**Comment by Gegy** [comment]
Did you maybe create a new world with difference settings?
If you want to avoid this problem, though, you can install the CubicChunks mod alongside Terrarium which allows for infinite height ranges. You'll need to create a new world once its installed, though

**Comment by VisionaryMind** [comment]
I think I see what's happening. Yesterday, we were using the default Terrarium scale and the new builds are being set to 1:1 scale. So it's probably the elevations at 1:1 scale that are throwing it off. I will need to enlarge the world scale. Will that break anything. Is the Tall Worlds mod compatible with Terrarium? Or perhaps the better approach would be to lower the default elevation point so that it doesn't hit the the top at 1:1.

**Comment by VisionaryMind** [comment]
You just answered my question. Thank you. CubicChunks.

**Comment by Gegy** [comment]
Cool :)
